name: eco
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  camera: ^0.11.2
  file_picker: ^10.3.1
  firebase_core: ^4.1.0
  firebase_database: ^12.0.1
  firebase_auth: ^6.1.0
  tflite_flutter: ^0.11.0
  image: ^4.5.4
  image_picker: ^0.8.4+11
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  google_fonts: ^6.1.0
  flutter_local_notifications: ^19.4.2
  shared_preferences: ^2.5.3
  google_maps_flutter: ^2.5.0
  geocoding: ^2.1.0
  location: ^5.0.3
  flutter_rating_bar: ^4.0.1
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.0   #Screen Responsive
  native_exif: ^0.6.2
  encrypt: ^5.0.1
  syncfusion_flutter_xlsio: ^31.2.5
  file_storage: ^1.0.0
  flutter_localization: ^0.3.3
  video_player: ^2.6.0
  intl: any
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: 1.26.2

  integration_test:
    sdk: flutter
  mockito: ^5.5.0

flutter:
  generate: true
  uses-material-design: true

  assets:
     - assets/
